Disable keep-alive in HttpClient (backport `dd-trace-dotnet` 5810) (#122)
This is a backport of the following PR from `dd-trace-dotnet`:
https://github.com/DataDog/dd-trace-dotnet/pull/5810

It appears that with .NET 6 there was a change in behavior for
HttpClient and it can cause the following error show up:

```
System.Net.Http.HttpIOException: The response ended prematurely. (ResponseEnded)
```

There is a pending escalation that appears to be using this NuGet
package and getting this error - which we initially thought was coming
from `dd-trace-dotnet`.

Note: I didn't have push access here so had to fork and then PR.